// Brain - Strategy file I/O + equipment data
// Claude Code is the brain. This module only provides:
// 1. Strategy file read/write (db/strategies/master-strategy.md)
// 2. Shop/equipment data for upgrade decisions
// 3. Minimal fallback for legacy start_bot mode
import 'dotenv/config';
import * as memory from './memory.mjs';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

const STRATEGY_DIR = join(process.cwd(), 'db', 'strategies');
const STRATEGY_FILE = join(STRATEGY_DIR, 'master-strategy.md');

function ensureDir(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

// ====== STRATEGY FILE I/O ======

export function getStrategy() {
  ensureDir(STRATEGY_DIR);
  if (!existsSync(STRATEGY_FILE)) return null;
  return readFileSync(STRATEGY_FILE, 'utf8');
}

export function updateStrategy(content) {
  ensureDir(STRATEGY_DIR);
  const old = getStrategy();
  if (old) {
    const backupFile = join(STRATEGY_DIR, `backup-${Date.now()}.md`);
    writeFileSync(backupFile, old, 'utf8');
  }
  writeFileSync(STRATEGY_FILE, content, 'utf8');
  return true;
}

// ====== INITIAL STRATEGY GENERATOR ======
// Scans the game and creates a strategy from scratch when none exists

export function generateInitialStrategy(gameData) {
  const { player, crimes, weather, events, quests, shops, junkyard } = gameData;

  const p = player || {};
  const level = p.level || 1;
  const money = p.money || 0;
  const energy = p.energy || 0;
  const maxEnergy = p.maxEnergy || 12;
  const stats = p.stats || {};
  const equipped = p.equipped || {};
  const addiction = Math.round(p.addiction || 0);

  // Analyze available crimes
  const availableCrimes = (crimes || [])
    .filter(c => c.requiredLevel <= level)
    .sort((a, b) => b.energyCost - a.energyCost);

  const crimeTable = availableCrimes.map(c => {
    const avgMoney = (c.minimumMoney + c.maximumMoney) / 2;
    const avgXp = (c.minimumExp + c.maximumExp) / 2;
    const efficiency = (avgMoney / c.energyCost).toFixed(1);
    return `- ${c.energyCost}+ energy → ${c.id} ($${c.minimumMoney}-${c.maximumMoney}, ${c.minimumExp}-${c.maximumExp}XP, ~$${efficiency}/E)`;
  }).join('\n');

  // Find next crime unlock
  const nextCrime = (crimes || []).find(c => c.requiredLevel > level);
  const nextUnlock = nextCrime ? `Next crime unlocks at level ${nextCrime.requiredLevel}: ${nextCrime.id} (${nextCrime.energyCost}E, $${nextCrime.minimumMoney}-${nextCrime.maximumMoney})` : 'All crimes unlocked!';

  // Analyze weakest stat
  const statEntries = Object.entries(stats).sort(([, a], [, b]) => a - b);
  const weakestStat = statEntries[0] || ['strength', 0];
  const strongestStat = statEntries[statEntries.length - 1] || ['strength', 0];

  // Equipment analysis
  const upgrades = getEquipmentUpgrades(p);
  const upgradeList = upgrades.slice(0, 3).map(u =>
    `- ${u.slot}: ${u.item.id} from ${u.item.shop} ($${u.item.price}, power +${itemPower(u.item.stats)})`
  ).join('\n') || '- No affordable upgrades right now';

  // Hooker income
  const hookers = p.hookers || [];
  const hookerInfo = hookers.length > 0
    ? hookers.map(h => `${h.name}: $${h.hourlyRate}/hr, uncollected $${(h.uncollected_profits || 0).toFixed(0)}`).join(', ')
    : 'None';

  // Quest analysis
  const questList = (quests || []).map(q => {
    const status = q.completedAt ? 'CLAIMED' : q.completed ? 'DONE (claim it!)' : `${q.progress}/${q.required}`;
    return `- ${q.name} [${q.key}]: ${status} → +${q.rewardReputation}R`;
  }).join('\n') || '- No quests available';

  // Weather effects
  const weatherInfo = weather
    ? `${weather.weather?.type}, ${weather.weather?.temperatureC}°C, period: ${weather.period}`
    : 'Unknown';

  const strategy = `# Crime.Life Bot Strategy v1.0

> Auto-generated by scanning the game. Claude Code will evolve this over time.
> Generated for: ${p.username || 'Unknown'} (Level ${level})
> Date: ${new Date().toISOString().split('T')[0]}

## Player Snapshot
- Level ${level}, $${money}, ${p.respect || 0} respect
- Stats: ${Object.entries(stats).map(([k, v]) => `${k.toUpperCase().slice(0, 3)}=${v}`).join(' ')}
- Equipped: weapon=${equipped.weapon || 'none'}, armor=${equipped.armor || 'none'}, equipment=${equipped.equipment || 'none'}
- Max Energy: ${maxEnergy}
- Addiction: ${addiction}%
- Hookers: ${hookerInfo}

## Priority Rules (highest to lowest)

### 1. EMERGENCY: Prison & Hospital
- If in PRISON → wait (release is timed, no escape)
- If in HOSPITAL → heal. If fails, try instant_release. If both fail, wait.

### 2. ENERGY MANAGEMENT
When energy is 0:
- If addiction < 70% and money >= $1000 → join club (the-gutter) then buy methamphetamine (+150E)
- If addiction < 70% and money >= $815 → join club then buy ketamine (+125E)
- If addiction < 70% and money >= $625 → join club then buy fentanyl (+100E)
- If addiction >= 70% → DO NOT buy drugs. Wait for natural regen + do downtime tasks.
- IMPORTANT: Must join_club BEFORE buy_drug
- Energy regens ~1 per 5 minutes naturally

### 3. MORNING TRAINING (period = "morning")
- +20% training efficiency during morning — always train if energy >= 5
- Weakest stat: ${weakestStat[0]} (${weakestStat[1]}) — train this first
- Training IDs: neighborhood-gym-visit (strength), practicing-safe-cracking (intelligence)
- Cost: 5 energy + $500

### 4. CRIMES (primary activity)
Best crime by available energy (level ${level}):
${crimeTable}

${nextUnlock}

### 5. DOWNTIME (energy = 0, can't buy drugs)
Priority order:
1. Craft junkyard items (free stats! See section below)
2. Collect hooker profits (when >= $3)
3. Claim completed daily quests
4. Buy & equip gear upgrades
5. Review and evolve this strategy
6. Save learnings to memory
7. Wait for energy regen

### 6. JUNKYARD CRAFTING
Key crafting chains for free stats and money:
- dirty_tissue x30 ($100) → paperclip → paperclip x5 ($0) → fingers-gloves → USE → +1 INT
- worn_out_sock x35 ($100) → cotton_scrap → cotton_scrap x5 ($100) → hoodie → USE → +1 IMUN
- used_popsicle_stick x10 ($100) → handful_of_sugar → sugar x5 ($100) → lollipop → USE → +$1000

API notes:
- Craft: POST /junkyard/craft {"recipeId": "id"} (camelCase)
- Use: POST /consumables/use {"consumable_id": "id"} (snake_case)

### 7. EQUIPMENT
Current loadout: ${equipped.weapon || 'none'} / ${equipped.armor || 'none'} / ${equipped.equipment || 'none'}

Affordable upgrades:
${upgradeList}

Shop prices have time-of-day modifier. Night = 1.1x more expensive.

### 8. DAILY QUESTS
${questList}

### 9. BANKING
- Keep cash on hand for drugs, training, and equipment
- Deposit excess when > $10,000 and no upgrades needed

### 10. PVP
- Only attack targets within 3 levels
- Focus on leveling and stats before PvP
- Adding targets requires both players in same nightclub

## Weather & Events
- Current: ${weatherInfo}
- Morning = +20% training, Rain = +5% crime success, Night = 1.3x crime modifier

## Evolution Log
- v1.0: Auto-generated from game scan
`;

  updateStrategy(strategy);
  return strategy;
}

// ====== SHOP DATA ======

const SHOP_ITEMS = {
  weapon: [
    { id: 'rusty_kitchen_knife', shop: 'neighborhood-hardware', price: 44, stats: { strength: 2 } },
    { id: 'radiant-sun-katana', shop: 'gold-line-armaments', price: 79, stats: { strength: 2, intelligence: 3 } },
    { id: 'frost-blade', shop: 'silver-mercenary-reserve', price: 75, stats: { strength: 2, intelligence: 2 } },
    { id: 'lead_pipe', shop: 'neighborhood-hardware', price: 225, stats: { strength: 4, intimidation: 1 } },
    { id: 'cheap_38_revolver', shop: 'neighborhood-hardware', price: 450, stats: { strength: 10, intimidation: 2 } },
    { id: 'noisy_hi_point', shop: 'neighborhood-hardware', price: 540, stats: { strength: 12 } },
    { id: '9mm_pistol_filed', shop: 'steel-and-fury', price: 3000, stats: { strength: 50 } },
    { id: 'sawed_off_shotgun', shop: 'steel-and-fury', price: 7000, stats: { strength: 60, intimidation: 10 } },
    { id: 'blackmarket_uzi', shop: 'steel-and-fury', price: 11000, stats: { strength: 95, intimidation: 15 } },
    { id: 'worn_ak47', shop: 'steel-and-fury', price: 15000, stats: { strength: 120, intimidation: 30 } },
    { id: 'police_issue_glock19', shop: 'peacemakers-inc', price: 45000, stats: { strength: 280, intelligence: 20 } },
    { id: 'silver-fang-pistol', shop: 'silver-mercenary-reserve', price: 76500, stats: { strength: 250, intelligence: 100, intimidation: 100 } },
    { id: 'tactical_m4', shop: 'peacemakers-inc', price: 112500, stats: { strength: 400, intelligence: 50 } },
    { id: 'whisper_silenced_45', shop: 'peacemakers-inc', price: 137500, stats: { strength: 450, intelligence: 100 } },
    { id: 'remington700', shop: 'peacemakers-inc', price: 175000, stats: { strength: 550, intelligence: 150 } },
    { id: 'desert_eagle_skullcrusher', shop: 'stolen-prototypes', price: 480000, stats: { strength: 1000, intimidation: 200 } },
    { id: 'gilded-executor-pistol', shop: 'gold-line-armaments', price: 630000, stats: { strength: 600, intelligence: 400, intimidation: 400 } },
    { id: 'reaper_lmg', shop: 'stolen-prototypes', price: 1600000, stats: { strength: 1700, intimidation: 300 } },
    { id: 'barrett_gravedigger', shop: 'stolen-prototypes', price: 2560000, stats: { strength: 2500, intelligence: 500, intimidation: 200 } },
    { id: 'mercury-wolf-smg', shop: 'silver-mercenary-reserve', price: 4225000, stats: { strength: 3500, intelligence: 1500, intimidation: 1500 } },
  ],
  armor: [
    { id: 'thick_leather_jacket', shop: 'neighborhood-hardware', price: 140, stats: { resistence: 4 } },
    { id: 'reinforced_biker_jacket', shop: 'neighborhood-hardware', price: 315, stats: { resistence: 6, intimidation: 1 } },
    { id: 'strapped_metal_plates', shop: 'neighborhood-hardware', price: 450, stats: { resistence: 10 } },
    { id: 'padded_gang_vest', shop: 'neighborhood-hardware', price: 900, stats: { resistence: 12, intimidation: 8 } },
    { id: 'used_level2_vest', shop: 'steel-and-fury', price: 6000, stats: { resistence: 60 } },
    { id: 'light_tactical_vest', shop: 'steel-and-fury', price: 9000, stats: { resistence: 90 } },
    { id: 'battleship_vest', shop: 'steel-and-fury', price: 14000, stats: { resistence: 120, intimidation: 30 } },
    { id: 'concealed_kevlar', shop: 'peacemakers-inc', price: 64000, stats: { intelligence: 20, resistence: 300 } },
    { id: 'sterling-carapace', shop: 'silver-mercenary-reserve', price: 76500, stats: { resistence: 400, imunity: 50 } },
    { id: 'interceptor_ceramic', shop: 'peacemakers-inc', price: 125000, stats: { resistence: 500 } },
    { id: 'luxury_ballistic_suit', shop: 'peacemakers-inc', price: 150000, stats: { resistence: 500, intimidation: 100 } },
    { id: 'gold-plated-vest', shop: 'gold-line-armaments', price: 630000, stats: { resistence: 1200, imunity: 200 } },
    { id: 'combat_armor_russian', shop: 'stolen-prototypes', price: 900000, stats: { strength: 100, resistence: 1800 } },
    { id: 'juggernaut_vest', shop: 'stolen-prototypes', price: 1760000, stats: { resistence: 2000, intimidation: 200 } },
    { id: 'eod_combat_armor', shop: 'stolen-prototypes', price: 2400000, stats: { resistence: 2800, imunity: 200 } },
    { id: 'titan_exoskeleton', shop: 'stolen-prototypes', price: 2880000, stats: { strength: 500, resistence: 2800, intimidation: 300 } },
    { id: 'mercenary-guard', shop: 'silver-mercenary-reserve', price: 4125000, stats: { resistence: 4500, intimidation: 500, imunity: 500 } },
  ],
  equipment: [
    { id: 'crowbar', shop: 'neighborhood-hardware', price: 270, stats: { strength: 6 } },
    { id: 'rapid_restraint_kit', shop: 'neighborhood-hardware', price: 360, stats: { imunity: 8 } },
    { id: 'beginners_lockpick_kit', shop: 'neighborhood-hardware', price: 675, stats: { intelligence: 15 } },
    { id: 'reinforced_duffel_bag', shop: 'neighborhood-hardware', price: 810, stats: { resistence: 18 } },
    { id: 'silent_electric_drill', shop: 'neighborhood-hardware', price: 1800, stats: { strength: 15, intelligence: 25 } },
    { id: 'first_aid_kit', shop: 'steel-and-fury', price: 4400, stats: { resistence: 45, imunity: 10 } },
    { id: 'modular_trauma_plate', shop: 'steel-and-fury', price: 8000, stats: { resistence: 80 } },
    { id: 'adrenaline_auto_injector', shop: 'steel-and-fury', price: 25000, stats: { resistence: 200, imunity: 50 } },
    { id: 'card_cloning_device', shop: 'peacemakers-inc', price: 87500, stats: { intelligence: 350 } },
    { id: 'smoke_grenade_belt', shop: 'peacemakers-inc', price: 105000, stats: { intelligence: 420 } },
    { id: 'demolition_kit', shop: 'peacemakers-inc', price: 120000, stats: { strength: 180, intelligence: 300 } },
    { id: 'signal_jammer', shop: 'stolen-prototypes', price: 240000, stats: { intelligence: 800 } },
    { id: 'midas-flashbangs', shop: 'gold-line-armaments', price: 652500, stats: { intelligence: 1450 } },
    { id: 'moonsliver-garrote', shop: 'silver-mercenary-reserve', price: 76500, stats: { intelligence: 450 } },
    { id: 'night_thermal_goggles', shop: 'stolen-prototypes', price: 1260000, stats: { intelligence: 1800 } },
    { id: 'surveillance_micro_drones', shop: 'stolen-prototypes', price: 2000000, stats: { intelligence: 2500 } },
    { id: 'hacker_laptop', shop: 'stolen-prototypes', price: 3040000, stats: { intelligence: 3800 } },
    { id: 'quicksilver-injector', shop: 'silver-mercenary-reserve', price: 4550000, stats: { strength: 1500, intelligence: 4000, intimidation: 1500 } },
  ],
};

function itemPower(stats) {
  if (!stats) return 0;
  return (stats.strength || 0) + (stats.intelligence || 0) + (stats.resistence || 0)
    + (stats.intimidation || 0) + (stats.imunity || 0);
}

function findBestUpgrade(slot, equippedItemId, money) {
  const items = SHOP_ITEMS[slot] || [];
  const currentItem = items.find(i => i.id === equippedItemId);
  const currentPower = currentItem ? itemPower(currentItem.stats) : 0;
  const budget = money * 0.7;
  return items
    .filter(i => i.price <= budget && itemPower(i.stats) > currentPower)
    .sort((a, b) => itemPower(b.stats) - itemPower(a.stats))[0] || null;
}

export function getEquipmentUpgrades(player) {
  const money = player?.money || 0;
  const equipped = player?.equipped || {};
  const upgrades = [];
  for (const slot of ['weapon', 'armor', 'equipment']) {
    const upgrade = findBestUpgrade(slot, equipped[slot], money);
    if (upgrade) upgrades.push({ slot, item: upgrade });
  }
  return upgrades.sort((a, b) => itemPower(b.item.stats) - itemPower(a.item.stats));
}

// ====== LEGACY: minimal fallback for start_bot mode ======
// When start_bot is used without Claude Code, these provide basic gameplay

export async function decideNextAction(gameState) {
  const p = gameState.player;
  if (!p) return { action: 'wait', params: { seconds: 10 }, reasoning: 'No player data' };
  if (p.prison?.status) return { action: 'wait', params: { seconds: 30 }, reasoning: 'In prison' };
  if (p.hospital?.status) return { action: 'heal', params: {}, reasoning: 'In hospital' };
  if (p.energy <= 0) {
    if (p.money >= 625 && (p.addiction || 0) < 70) {
      return { action: 'buy_drug', params: { clubId: 'the-gutter', drugId: 'fentanyl' }, reasoning: 'No energy, buying fentanyl', _needsClubJoin: true };
    }
    return { action: 'wait', params: { seconds: 60 }, reasoning: 'No energy, waiting for regen' };
  }
  const crimes = gameState.crimes?.crimes?.filter(c => c.requiredLevel <= p.level && c.energyCost <= p.energy) || [];
  const best = crimes.sort((a, b) => b.requiredLevel - a.requiredLevel)[0];
  return { action: 'commit_crime', params: { crimeId: best?.id || 'steal-candy-from-a-child' }, reasoning: 'Best crime by level' };
}

export async function planSession(fullGameState) {
  const level = fullGameState.player?.level || 1;
  const plan = {
    phase: level < 20 ? 'foundation' : level < 40 ? 'growth' : 'aggression',
    goals: ['Commit crimes for XP and money', 'Train weakest stat', 'Complete daily quests'],
    actionPlan: [
      { step: 1, action: 'commit_crime', reason: 'Primary income and XP source' },
      { step: 2, action: 'train', reason: 'Improve weakest stat' },
      { step: 3, action: 'daily_quest', reason: 'Bonus rewards' },
    ],
    focusStat: 'strength',
    socialStrategy: 'Stay low profile',
  };
  memory.saveMemory('strategies', 'current-session-plan', JSON.stringify(plan, null, 2));
  return plan;
}

export async function analyzeCombat(combatResult, enemyProfile) {
  return {
    outcome: combatResult?.won ? 'win' : 'lose',
    lesson: combatResult?.won ? 'Victory' : 'Need more training',
    enemyThreat: combatResult?.won ? 3 : 8,
    shouldAttackAgain: !!combatResult?.won,
    statToTrain: 'strength',
  };
}

export async function evolveStrategy() {
  return false; // Claude Code handles strategy evolution directly
}

export function selectBestCrime(crimes, playerStats) {
  const available = (crimes?.crimes || [])
    .filter(c => c.requiredLevel <= (playerStats?.level || 1) && c.energyCost <= (playerStats?.energy || 12))
    .sort((a, b) => b.requiredLevel - a.requiredLevel);
  return { crimeId: available[0]?.id || 'steal-candy-from-a-child' };
}
